defaults: &defaults
  name: "Censored Tweets"
  twitter_consumer_key: XNCsleBNGax7h2tQK7vl7Q
  twitter_consumer_secret: 5udErzH5pCScJE5qdy7zGhzqDtQO8zjrM2sPbo4HkU
  mongo_server: 'localhost'
  mongo_port: 27017
  mongo_pool_size: 40
  mongo_db_name: "ct-production"
  
development:
  domain: localhost:3000
  mongo_db_name: "ct-development"
  <<: *defaults

test:
  domain: test.host
  mongo_db_name: "ct-test"
  <<: *defaults

staging:
  domain: stage.censoredtweets.com
  <<: *defaults

production:
  domain: censoredtweets.com
  mongo_server: "staff.mongohq.com"
  mongo_port: 10007
  mongo_db_name: "app578915"
  mongo_username: "heroku"
  mongo_password: "yihgyonou6471n2uheeqe8"
  <<: *defaults
  
